import pandas as pd
import math

def n_fold_cross_validation(df, n):
    '''
    return a set of each iteration of feature-label randomly generated by cross validation algorithm
`
    :param xy: contans features (list of lists which each represent a row of feature and 
        all the labels for the according features) - labels should be the first column
    :param n: amount of iterations of validations/size of each testing set
    '''
    n_size = len(df) / n
    n_sets = []
    n_train_test_sets = []
    df = df.sample(frac=1, random_state=42)

    for i in range(1, n + 1):
        start = int(math.floor(i * n_size - n_size))
        end = int(math.floor(i * n_size))

        n_sets.append(df.iloc[start:end, :])

    for i in range(n):
        train_test = [0, n_sets[i]]

        test = df.drop(df.index)
        for j in range(n):
            if (j != i):
                test = pd.concat([test, n_sets[j]], ignore_index=True)
        train_test[0] = test
        
        n_train_test_sets.append(train_test)
    
    return n_train_test_sets
            