
def n_fold_cross_validation(xy, n):
    '''
    return a set of each iteration of feature-label randomly generated by cross validation algorithm
`
    :param xy: contans features (list of lists which each represent a row of feature and 
        all the labels for the according features) - labels should be the first column
    :param n: amount of iterations of validations/size of each testing set
    '''
